FROM ubuntu:latest

RUN echo 'nameserver 1.1.1.1' > /etc/resolv.conf && apt-get update && apt-get upgrade -y && apt-get install -y \
    git \
    curl \
    nano

ENV LANG=C.UTF-8 LC_ALL=C.UTF-8

RUN useradd -ms /bin/bash newuser
USER newuser
WORKDIR /home/newuser
